<div class="page-title category-title">
        <h1>Featured Customer Designs</h1>
</div>

<div style="margin-top:20px; margin-bottom:20px; margin-left:40px; margin-right:40px;"><p>Our customers are a talented bunch and we love seeing the designs that they come up with! Here we showcase the custom Magic Band Skins that previous customers have created. Not only can you be inspired by these designs but you can use these designs as a starting point for your own or purchase as they are.</p>

<p>Do you have a custom Magic Band that you want featured here? Please <a title="contact us" href="<?php echo Mage::getBaseUrl(); ?>contacts">contact us</a>.</p>


</div>

