<?php if ($this->getQuote()->isVirtual()) : return; endif; ?>
<h2 class="title-shipping-method"><?php echo $this->__('Shipping Method'); ?></h2>
<div id="shipping-method" class="fancycheckout_block">
    <div class="opc_shipping_method_content"> 
        <div class="opc_available_additional">   
            <div id="checkout-shipping-method-load">
                <?php echo $this->getChildHtml('available') ?>
            </div>
            <div id="onepage-checkout-shipping-method-additional-load">
                <?php echo $this->getChildHtml('additional') ?>
            </div>
        </div>
        <div style="clear: both;"></div>
    </div>
    <div style="clear: both;"></div>
</div>