<?php if ($this->getTotals()): ?>
	<div class="offcanvascheckout-subtotal">
        <?php echo $this->__('Subtotal') ?> : 
        <span class="value">
            <?php   
                $session = Mage::getSingleton('checkout/session');
                $totals = Mage::getSingleton('checkout/session')->getQuote()->getTotals(); //Total object
                echo Mage::helper('core')->currency($totals["subtotal"]->getValue(), true, false);
            ?>
        </span>
    </div>
<?php endif; ?>
