<?php if (!Mage::getSingleton('customer/session')->isLoggedIn()){?>
    <div id="offcanvascheckout_loginbox"  class='customer_login'>
        <div class="page-title">
            <strong><?php echo $this->__('Login to your Account') ?></strong>
        </div>
        <?php
            $login_url	= $this->getUrl('fancycheckout/offcanvascheckout/login', array('_secure'=>(!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS']==='on')));
            $http_mode	= (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS']==='on');
            if($http_mode)$login_url	= str_replace('http:', 'https:', $login_url);  
        ?>
        <form method="POST" name="login-form" id="login-form-mst">
            <div class="boxcontent form_fields">
    			<div class='full field'>
    				<label>
    					<?php echo $this->__('Email Address') ?> <em>*</em>
    				</label>
    				
    				<div class="input-box">
    					<input type="text" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
    				</div>
    			</div>
    			<div class='full field'>
    				<label>
    					<?php echo $this->__('Password') ?> <em>*</em>
    				</label>
    				
    				<div class="input-box">
    					<input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
    				</div>
    			</div>
                <div class="login-message error-msg" style="display: none;"></div>
            </div>
            <div class="buttons-set">
                <a href="javascript:void(0);" class="offcanvascheckout_password_link f-left"><?php echo $this->__('Forgot Your Password?') ?></a>
                <button type="button" class="button" title="<?php echo $this->__('Login') ?>" onclick="loginForm.submit(this)"><span><span><?php echo $this->__('Login') ?></span></span></button>
            </div>
        </form>
        <script type="text/javascript">
        //<![CDATA[
            var loginForm = new VarienForm('login-form-mst');
            //ajax saveorder
            jQuery(document).ready(function($){
                loginForm.submit = function() {
            		if(this.validator.validate()){
            			data = $('#login-form-mst').serialize();
                        if(typeof ajax_request !== 'undefined')
                        ajax_request.abort();
                        ajax_request = $.ajax({
                        	type: "POST",
                        	url: "<?php echo $login_url;?>",
                        	data: data,
                        	cache: false,
                            beforeSend:  function() {
                                $('.loading-product-cart').show();
                                $('.cart-step-content').css('opacity','0.2');
                                $('.shipping-step-content').css('opacity','0.2');
                                $('.review-step').css('opacity','0.2');
                                $('.login-forget').css('opacity','0.2');
                            },
                            success: function(html){                                
                                var _json = $.parseJSON(html); 
                                if(_json.success == true){
                                    url = $('#mst-address-request').val()+'fancycheckout/offcanvascheckout/reloadlogin';                                                                         
                                    $.ajax({
                                    	type: "POST",
                                    	url: url,
                                    	data: data,
                                    	cache: false,
                                        beforeSend:  function() {
                                                                                                                                    
                                        },
                                        success: function(html){  
                                            var _json = $.parseJSON(html); 
                                            $('.cart-step-content-load').html(_json.info);   
                                            $('.shipping-step-content-load').html(_json.shippingaddress);  
                                            $('.review-step-shipping').html(_json.shipping_method);  
                                            $('.review-step-payment').html(_json.payment_method);  
                                            $('.review-step-review').html(_json.review_order);   
                                            //Update header and slidebar cart 
                                            MST.updateToplink(_json.topLinks);
                                            MST.minicarthead(_json.minicarthead);
                                            if(_json.sidebar){
                                				if($('.sidebar > .block-cart').length){								
                                					$('.sidebar > .block-cart').replaceWith(_json.sidebar);					
                                				}
                                				if($('.header-primary #mini-cart').length && MST.checkThemMagento('ultimo')){
                                					$('.header-primary #mini-cart').replaceWith(_json.sidebar);
                                					MST.ReloadScriptsUltimo();
                                				}
                                			}
                                            MST.showFancycheckout();   
                                            //-------------------------
                                            $('.offcanvascheckout-login-link').hide();
                                            $('.offcanvas-checkout-login-form').hide();
                                            $('.offcanvas-checkout-forget-pass-form').hide();  
                                            $('.loading_image').hide();
                                            $('.cart-step-content').css('opacity','1');
                                            $('.shipping-step-content').css('opacity','1');
                                            $('.review-step').css('opacity','1');
                                            $('.login-forget').css('opacity','1');                                                                                  
                                        }
                                    });                                                                                                
                                }else{
                                    $('.login-message').show();
                                    $('.login-message').html(_json.error);
                                    $('.loading_image').hide();
                                    $('.cart-step-content').css('opacity','1');
                                    $('.shipping-step-content').css('opacity','1');
                                    $('.review-step').css('opacity','1');
                                    $('.login-forget').css('opacity','1');  
                                }
                            }
                        });
            		}
            	}.bind(loginForm);
             });
        //]]>
        </script>
		<div class="close-login-popup" >
			<span style="float: right; text-decoration: underline; font-weight: bold; color: rgb(0, 0, 0); cursor: pointer;" ><?php echo $this->__('Close'); ?></span>
		</div>
		<div style="clear: both;"></div>
    </div>
<?php }?>