<?php
    $url_request = $this->getUrl('', array('_secure'=>(!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS']==='on')));
    $http_mode	= (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS']==='on');
    if($http_mode)$url_request = str_replace('http:', 'https:', $url_request);  
?>
<input type="hidden" id="mst-address-request" value="<?php echo $url_request; ?>" />
<?php if ( Mage::getStoreConfig('fancycheckout/layout_configuration/offcanvas_checkout') ) { ?>
    <script src="<?php echo $this->getSkinUrl('fancycheckout/js/offcanvas_checkout.js'); ?>" type="text/javascript"></script>
    <!--<div style="float: left; clear: both; padding: 10px; background: red; cursor: pointer; color: #fff;" class="show-offcanvas-checkout"> Show Offcanvas Checkout  </div>-->
    <?php 
        $title_terms_conditions = trim(Mage::getStoreConfig('fancycheckout/terms_conditions/title'));
        $content = trim(Mage::getStoreConfig('fancycheckout/terms_conditions/content'));
        $enable_custom_size = trim(Mage::getStoreConfig('fancycheckout/terms_conditions/enable_custom_size'));
        $width = trim(Mage::getStoreConfig('fancycheckout/terms_conditions/width'));
        $height = trim(Mage::getStoreConfig('fancycheckout/terms_conditions/height'));
        //Registration 
        $registration = trim(Mage::getStoreConfig('fancycheckout/registration/type'));
        //Login
        $login = trim(Mage::getStoreConfig('fancycheckout/registration/show_login'));
    ?>
    <style>
        .term_conditions{
            <?php if($enable_custom_size){ ?>
                width: <?php echo $width.'px' ?>;
                height: <?php echo $height.'px' ?>;
            <?php }else{ ?>
                width: 500px;
                height: 500px;
            <?php } ?>
            position: fixed;
            border: 1px solid silver;
            border-radius: 10px;
            background: white;
            top: 100px;
            display: none;
            z-index: 10010;
            padding: 10px 10px 20px ; 
            transform: translateX(-50%);
            left: 50%;
        }
    </style>
    <div class="control-overlay"></div>
    <div class="term_conditions">
    	<h5><?php echo $title_terms_conditions; ?></h5>
        <?php echo $content;?>
        <p class="close">
            <a href="#"><?php echo $this->__('Close') ?></a>
        </p>
    </div>
    <div class="offscreen step1" >
    	<span class="close-offcanvas-checkout fa fa-times"><?php //echo $this->__('CLOSE'); ?></span>
    	<div class="clear" ></div>
        <!-- cart step -->
    	<div id="cart-step" class="step-offcanvas-checkout" style="display: none;" >
            <?php if($login){?>
                <?php if($registration !=2 ){if (!Mage::getSingleton('customer/session')->isLoggedIn()){?><div class="offcanvascheckout-login-link" ><?php echo $this->__('Already registered?'); ?> <a href="javascript:void(0);" class="offcanvascheckout_login"><?php echo $this->__('Please login here'); ?></a></div><?php }}?>
                <div class="login-forget">
                    <div class="offcanvas-checkout-login-form" style="display: none;"><?php echo  Mage::app()->getLayout()->getBlock('customer_form_login_mst')->toHtml()?></div>
                    <div class="offcanvas-checkout-forget-pass-form" style="display: none;"><?php echo  Mage::app()->getLayout()->getBlock('customer_account_forgotpassword_mst')->toHtml()?></div>
                    <div style="clear: both;"></div>
                </div>
            <?php } ?>
            <div class="loading_image loading-product-cart" style="display: none;">
                <img src="<?php echo $this->getSkinUrl('fancycheckout/images/loading.gif') ?>" />
            </div>
    		<div class="cart-step-content" >
        		<h2 class="title-shopping-cart"><?php echo $this->__('Shopping Cart'); ?></h2>
                <div class="cart-step-content-load">
                    <!--Display-->
                    <?php echo  Mage::app()->getLayout()->getBlock('review_info')->toHtml()?>
                </div>
    		</div>
    		<button type="button" class="button goto-shipping-step offcanvas-checkout-button" data-target="shipping" ><span><span><?php echo $this->__('Go to Shipping'); ?></span></span></button>
    		<button class="button close-off-canvas offcanvas-checkout-button" type="button"><span><span><?php echo $this->__('Go Buy Something'); ?></span></span></button>
    	</div>
        <form action="<?php echo $url_request.'fancycheckout/offcanvascheckout/saveOrder';?>" method="POST" name="offcanvas-checkout" id="offcanvas-checkout">
        	<!-- shipping step -->
            <div id="shipping-step" class="step-offcanvas-checkout" style="display: none; " >
                <div class="loading_image loading-shipping-address" style="display: none;">
                    <img src="<?php echo $this->getSkinUrl('fancycheckout/images/loading.gif') ?>" />
                </div>
        		<div class="shipping-step-content" >
                    <div class="shipping-step-content-load">
                        <!--Display-->
                        <?php echo  Mage::app()->getLayout()->getBlock('frontend_checkout_address_billing_shipping')->toHtml()?>
                    </div>
        		</div>
        		<button type="button" class="button goto-review-step offcanvas-checkout-button" data-target="review" ><span><span><?php echo $this->__('Review Your Order'); ?></span></span></button>
        	</div>
            <!-- review step -->
        	<div id="review-step" class="step-offcanvas-checkout" style="display: none; " >
                <div class="loading_image loading-review" style="display: none;">
                    <img src="<?php echo $this->getSkinUrl('fancycheckout/images/loading.gif') ?>" />
                </div>
        		<div class="review-step">
            		<!--<h2 class="title-shipping-method"><?php echo $this->__('Shipping Method'); ?></h2>-->
                    <div class="review-step-shipping">
                        <!--Display-->
                        <?php echo  Mage::app()->getLayout()->getBlock('checkout_shipping_method')->toHtml()?>
                    </div>
            		<h2 class="title-payment-method"><?php echo $this->__('Payment Method'); ?></h2>
                    <div class="review-step-payment">
                        <!--Display-->
                        <?php echo  Mage::app()->getLayout()->getBlock('checkout_payment_method')->toHtml()?>
                    </div>
            		<h2 class="title-review"><?php echo $this->__('Review Your Order'); ?></h2>
                    <div class="review-step-review">
                        <!--Display-->
                        <?php echo  Mage::app()->getLayout()->getBlock('review_order')->toHtml()?>
                    </div>
                </div>
        		<?php if(trim(Mage::getStoreConfig('fancycheckout/general/newsletter_checkbox'))){?>
    				<div class="newsletter-signup">
    					<p class="newsletter">
    						<input type="checkbox" id="newsletter-signup" <?php if(trim(Mage::getStoreConfig('fancycheckout/general/newsletter_checkbox_cheked'))){echo "checked='checked'";} ?> name="newsletter" value="1" title="<?php echo Mage::helper('newsletter')->__('Sign up for our newsletter') ?>" class="checkbox" />
    						<label for="newsletter-signup">
    							<?php echo Mage::helper('newsletter')->__('Sign up for our newsletter') ?>
    						</label>
    					</p>
    				</div>
    			<?php } ?>
                <div id="checkout-review-submit">    
    				<button type="button" class="button offcanvas-checkout-button checkout-offcanvascheckout" data-target="review" onclick="shippingForm.submit(this)"><span><span><?php echo $this->__('Checkout'); ?></span></span></button>
                </div>  
            </div>
        </form>
        <script type="text/javascript">
            //< ![CDATA[
            var shippingForm = new VarienForm('offcanvas-checkout');
            //]]>
        </script> 
    </div>
    <script type="text/javascript">
        jQuery(document).ready(function($) {
            //show offcanvascheckout when goto website
            url = $('#mst-address-request').val()+'fancycheckout/offcanvascheckout/showoffcanvascheckout'; 
            $.ajax({
            	type: "POST",
            	url: url,
            	data : 'isAjax=1',
            	cache: false,
                beforeSend:  function() {
                },
                success: function(data){
                    var _json=$.parseJSON(data); 
                    $('.cart-step-content-load').html(_json.info);   
                    $('.shipping-step-content-load').html(_json.shippingaddress);  
                    $('.review-step-shipping').html(_json.shipping_method);  
                    $('.review-step-payment').html(_json.payment_method);  
                    $('.review-step-review').html(_json.review_order);   
                    <?php if (Mage::getSingleton('customer/session')->isLoggedIn()){ ?>  
                        var data = $('#offcanvas-checkout').serialize();
            			data += '&isAjax=1';
                        url = $('#mst-address-request').val()+'fancycheckout/offcanvascheckout/getshippingmethod';
            			$.ajax({
            				url: url,
            				type : 'post',
            				data : data,
                            cache: false,
                            beforeSend:  function() {
                            },
            				success : function(data) {
                                var _json = $.parseJSON(data);
                                $('.review-step-shipping').html(_json.shipping_method);  
                                $('.review-step-payment').html(_json.payment_method);                      
            				}
            			});  
                <?php } ?>          
                }
            });
            $('.offcanvascheckout_login').click(function(){
                $('.offcanvas-checkout-login-form').show();
                $('.offcanvas-checkout-forget-pass-form').hide();
            });
            $('.offcanvascheckout_password_link').click(function(){
                $('.login-message').hide();
                $('.offcanvas-checkout-login-form').hide();
                $('.offcanvas-checkout-forget-pass-form').show();
            });
            $('.offcanvascheckout_login_link').click(function(){
                $('.offcanvas-checkout-login-form').show();
                $('.offcanvas-checkout-forget-pass-form').hide();
            });
            $('.close-login-popup').click(function(){
                $('.login-message').hide();
                $('.offcanvas-checkout-login-form').hide();
            })
                                  
            //ajax add cart
            var productAddToCartForm1 = new VarienForm('product_addtocart_form');
            MST={
                showFancycheckout: function()
                {
                    $(' .top-link-cart , .top-link-checkout ').on( "click" , function() {	
                        return false;
                	});
                	$(' .show-offcanvas-checkout , .top-link-cart , .top-link-checkout , .skip-cart , #cart-step ').on( "click" , function() {	
                		$('body').addClass('active-offcanvas-checkout');
                		$('html').addClass('active-offcanvas-checkout');  
                		$('.control-overlay').show();	
                		$('.offscreen #cart-step').show();		
                		$('.offscreen').addClass('active');
                		$('.offscreen').removeClass('step2 step3');
                        $('.goto-shipping-step').show();
                		setTimeout(function () {
                			$('.offscreen #shipping-step').show();
                			$('.offscreen #review-step').show();  
                		}, 1000);
                	});
                },
                checkThemMagento: function(theme){
        			var scriptTag = document.getElementsByTagName('link');
        			var href;
        
        			for (var i = 0; i < scriptTag.length; i++) {
        				href = scriptTag[i].href;	
        				if(href.indexOf(theme.toString()) !== -1){
        					return true;
        					break;
        				}								
        			}
        			return	false;
        		},
                ReloadScripts: function(){
        			$('.skip-link').on('click', function (e) {
        				e.preventDefault();
        
        				var self = $(this);
        				var target = self.attr('href');
        
        				// Get target element
        				var elem = $(target);
        
        				// Check if stub is open
        				var isSkipContentOpen = elem.hasClass('skip-active') ? 1 : 0;
        
        				// Hide all stubs
        				$('.skip-link').removeClass('skip-active');
        				$('.skip-content').removeClass('skip-active');
        
        				// Toggle stubs
        				if (isSkipContentOpen) {
        					self.removeClass('skip-active');
        				} else {
        					self.addClass('skip-active');
        					elem.addClass('skip-active');
        				}
        			});
        
        			$('#header-cart').on('click', '.skip-link-close', function(e) {
        				var parent = $(this).parents('.skip-content');
        				var link = parent.siblings('.skip-link');
        
        				parent.removeClass('skip-active');
        				link.removeClass('skip-active');
        
        				e.preventDefault();
        			});
        		},
                ReloadScriptsUltimo: function(){
        			var dMenuPosTimeout;
        			var ddOpenTimeout;
        			$("#mini-cart.dropdown").hover(function() {
        				var ddToggle = $(this).children('.dropdown-toggle');
        				var ddMenu = $(this).children('.dropdown-menu');
        				var ddWrapper = ddMenu.parent();
        				ddMenu.css("left", "");
        				ddMenu.css("right", "");
        				if ($(this).hasClass('clickable-dropdown'))
        				{					
        					if ($(this).hasClass('open'))
        					{
        						$(this).children('.dropdown-menu').stop(true, true).delay(200).fadeIn(0, "easeOutCubic");
        					}
        				}
        				else
        				{					
        					clearTimeout(ddOpenTimeout);
        					ddOpenTimeout = setTimeout(function() {
        						
        						ddWrapper.addClass('open');
        						
        					}, 200);
        					
        					//$(this).addClass('open');
        					$(this).children('.dropdown-menu').stop(true, true).delay(200).fadeIn(0, "easeOutCubic");
        				}
        								
        				clearTimeout(dMenuPosTimeout);
        				dMenuPosTimeout = setTimeout(function() {
        
        					if (ddMenu.offset().left < 0)
        					{
        						var space = ddWrapper.offset().left; 
        						ddMenu.css("left", (-1)*space);
        						ddMenu.css("right", "auto");
        					}
        				
        				}, 200);
        			},function(){
        				var ddMenu = $(this).children('.dropdown-menu');
        				clearTimeout(ddOpenTimeout); 
        				ddMenu.stop(true, true).delay(0).fadeOut(0, "easeInCubic");
        				if (ddMenu.is(":hidden"))
        				{
        					ddMenu.hide();
        				}
        				$(this).removeClass('open');				
        			});
        		},
                updateToplink:function(topLinks){
        			if(topLinks){
        				if($('.header .quick-access > ul.links').length){
        					$('.header .quick-access > ul.links').replaceWith(topLinks);		
        				}				
        			}
        		},
                minicarthead:function(block){
        			if($('.header-minicart').length && MST.checkThemMagento('rwd')){
        				if(block){
        					$('.header-minicart').empty();						
        					$('.header-minicart').append(block);	
        					MST.ReloadScripts();	
        				}
        			}
        		},
        		buttonclickproductpage1: function(){
        			if(typeof(productAddToCartForm) != 'undefined'){
        				window.productAddToCartForm.submit = function(){	
        					if(productAddToCartForm1.validator && productAddToCartForm1.validator.validate()){
                                url = $('#product_addtocart_form').attr('action');
                                var validate_url1 = url.split("/updateItemOptions/");
                                var validate_url2 = url.split("/in_cart/");
                                if(validate_url1.length > 1)
                                {
                                    url = url.replace("checkout/cart/updateItemOptions","fancycheckout/offcanvascheckout/updateItemOptions");
                                }else{
                                    if(validate_url2.length > 1){
                                         url = url.replace("checkout/cart/add","fancycheckout/offcanvascheckout/updateItemOptions/id/<?php echo $this->getRequest()->getParam('id');?>");
                                    }else{
                                        url = url.replace("checkout/cart/add","fancycheckout/offcanvascheckout/add"); // New Code
                                    }
                                }
                    			var data = $('#product_addtocart_form').serialize();
                    			data += '&isAjax=1';
                    			try{
                    				$.ajax({
                    					url : url,
                    					type : 'post',
                    					data : data,
                                        beforeSend:  function() {
                                            $('body').addClass('active-offcanvas-checkout');
                                            $('html').addClass('active-offcanvas-checkout');										
                                    		$('.offscreen #cart-step').show();		
                                    		$('.offscreen').addClass('active');
                                    		$('.offscreen').removeClass('step2 step3');
                                            $('.goto-shipping-step').show();
                                            $('.loading-product-cart').show();
    										setTimeout(function () {
    											$('.offscreen #shipping-step').show();
    											$('.offscreen #review-step').show();  
    										}, 1000);
                                            $('.cart-step-content').css('opacity','0.2');
                                            $('.shipping-step-content').css('opacity','0.2');
                                            $('.review-step').css('opacity','0.2');
                                        },
                    					success : function(data) {
                    					    $('.loading_image').hide();
                                            $('.cart-step-content').css('opacity','1');
                                            $('.shipping-step-content').css('opacity','1');
                                            $('.review-step').css('opacity','1');
                                            var _json = $.parseJSON(data);
                                            if(_json.status == 'ERROR')
                                            {
                                                alert(_json.message);
                                            }
                                            $('body').addClass('active-offcanvas-checkout');
                                            $('html').addClass('active-offcanvas-checkout');
                                    		$('.control-overlay').show();		
                                    		$('.offscreen #cart-step').show();		
                                    		$('.offscreen').addClass('active');
                                    		$('.offscreen').removeClass('step2 step3');
                                            $('.cart-step-content-load').html(_json.info);
    										
    										setTimeout(function () {
    											$('.offscreen #shipping-step').show();
    											$('.offscreen #review-step').show();  
    										}, 1000);
    										
                                            $('.shipping-step-content-load').html(_json.shippingaddress);  
                                            $('.review-step-shipping').html(_json.shipping_method);  
                                            $('.review-step-payment').html(_json.payment_method);  
                                            $('.review-step-review').html(_json.review_order); 
                                            //Update header and slidebar cart
                                            MST.updateToplink(_json.topLinks);
                                            MST.minicarthead(_json.minicarthead);
                                            if(_json.sidebar){
                                				if($('.sidebar > .block-cart').length){								
                                					$('.sidebar > .block-cart').replaceWith(_json.sidebar);					
                                				}
                                				if($('.header-primary #mini-cart').length && MST.checkThemMagento('ultimo')){
                                					$('.header-primary #mini-cart').replaceWith(_json.sidebar);
                                					MST.ReloadScriptsUltimo();
                                				}
                                			}
                                            MST.showFancycheckout();
                                            <?php if (Mage::getSingleton('customer/session')->isLoggedIn()){ ?>  
                                                var data = $('#offcanvas-checkout').serialize();
                                    			data += '&isAjax=1';
                                                url = $('#mst-address-request').val()+'fancycheckout/offcanvascheckout/getshippingmethod';
                                    			$.ajax({
                                    				url: url,
                                    				type : 'post',
                                    				data : data,
                                                    cache: false,
                                                    beforeSend:  function() {
                                                    },
                                    				success : function(data) {
                                                        var _json = $.parseJSON(data);
                                                        $('.review-step-shipping').html(_json.shipping_method);   
                                                        $('.review-step-payment').html(_json.payment_method);                     
                                    				}
                                    			});  
                                        <?php } ?>  
                    					} 
                    				});
                    			}catch(e){}				
        					}
        				}	 
        			}	 
        		},
                buttonclickproductpage2: function(){
        			if(typeof(setLocation) != 'undefined'){
                		window.setLocation = function(url){
                            var validate= url.split("/add/");
                            if(validate.length >1 )
                            {
                            	url += 'isAjax/1';
                            	url = url.replace("checkout/cart/add","fancycheckout/offcanvascheckout/add"); // New Code
                            	data = 'isAjax=1';
                            	try{
                    				$.ajax({
                    					url : url,
                    					type : 'post',
                    					data : data,
                                        beforeSend:  function() {
                                            $('body').addClass('active-offcanvas-checkout');
                                            $('html').addClass('active-offcanvas-checkout');
                                    		$('.offscreen #cart-step').show();		
                                    		$('.offscreen').addClass('active');
                                    		$('.offscreen').removeClass('step2 step3');
                                            $('.goto-shipping-step').show();
                                            $('.loading-product-cart').show();
    										setTimeout(function () {
    											$('.offscreen #shipping-step').show();
    											$('.offscreen #review-step').show();  
    										}, 1000);
                                            $('.cart-step-content').css('opacity','0.2');
                                            $('.shipping-step-content').css('opacity','0.2');
                                            $('.review-step').css('opacity','0.2');
                                        },
                    					success : function(data) {
                    					    $('.loading_image').hide();
                                            $('.cart-step-content').css('opacity','1');
                                            $('.shipping-step-content').css('opacity','1');
                                            $('.review-step').css('opacity','1');
                                            var _json = $.parseJSON(data);
                                            if(_json.status == 'ERROR')
                                            {
                                                alert(_json.message);
                                            }
                                            $('body').addClass('active-offcanvas-checkout');
                                            $('html').addClass('active-offcanvas-checkout');
                                    		$('.control-overlay').show();		
                                    		$('.offscreen #cart-step').show();		
                                    		$('.offscreen').addClass('active');
                                    		$('.offscreen').removeClass('step2 step3');
                                            $('.cart-step-content-load').html(_json.info);
    										setTimeout(function () {
    											$('.offscreen #shipping-step').show();
    											$('.offscreen #review-step').show();  
    										}, 1000);
                                            $('.shipping-step-content-load').html(_json.shippingaddress);  
                                            $('.review-step-shipping').html(_json.shipping_method);  
                                            $('.review-step-payment').html(_json.payment_method);  
                                            $('.review-step-review').html(_json.review_order);
                                            //Update header and slidebar cart 
                                            MST.updateToplink(_json.topLinks);
                                            MST.minicarthead(_json.minicarthead);
                                            if(_json.sidebar){
                                				if($('.sidebar > .block-cart').length){								
                                					$('.sidebar > .block-cart').replaceWith(_json.sidebar);					
                                				}
                                				if($('.header-primary #mini-cart').length && MST.checkThemMagento('ultimo')){
                                					$('.header-primary #mini-cart').replaceWith(_json.sidebar);
                                					MST.ReloadScriptsUltimo();
                                				}
                                			}
                                            MST.showFancycheckout();                                        
                                            <?php if (Mage::getSingleton('customer/session')->isLoggedIn()){ ?>  
                                                var data = $('#offcanvas-checkout').serialize();
                                    			data += '&isAjax=1';
                                                url = $('#mst-address-request').val()+'fancycheckout/offcanvascheckout/getshippingmethod';
                                    			$.ajax({
                                    				url: url,
                                    				type : 'post',
                                    				data : data,
                                                    cache: false,
                                                    beforeSend:  function() {
                                                    },
                                    				success : function(data) {
                                                        var _json = $.parseJSON(data);
                                                        $('.review-step-shipping').html(_json.shipping_method); 
                                                        $('.review-step-payment').html(_json.payment_method);                       
                                    				}
                                    			});  
                                        <?php } ?> 
                    					} 
                    				});
                    			}catch(e){}	
                            }else{
                                window.location.replace(url);
                            }
                		}		
                	} 
        		}		
        	};
            MST.buttonclickproductpage1();
            MST.buttonclickproductpage2();    
            //ajax shipping step 
            $('.goto-shipping-step').bind('click',function(){
    			var data = $('#product_addtocart_form').serialize();
    			data += '&isAjax=1';
                url = $('#mst-address-request').val()+'fancycheckout/offcanvascheckout/stepshipping'; 
    			$.ajax({
    				url:url,
    				type : 'post',
    				data : data,
                    beforeSend:  function() {
                        $('.loading-product-cart').show();
                        $('.cart-step-content').css('opacity','0.2');
                    },
    				success : function(data) {
    				    //david
                        $('.offscreen').removeClass('step3');
                		$('.offscreen').addClass('step2');
                        $('.goto-shipping-step').hide();
                        $('.goto-review-step').show();    				    
                        //kien
                        $('.loading_image').hide();
                        $('.cart-step-content').css('opacity','1');
                        var _json = $.parseJSON(data);
                        $('.shipping-step-content-load').html(_json.shippingaddress);
    				}
    			});
            });
            //ajax review step
            $('.goto-review-step').bind('click',function(){
    			var data = $('#offcanvas-checkout').serialize();
    			data += '&isAjax=1';
                url = $('#mst-address-request').val()+'fancycheckout/offcanvascheckout/stepreview';
    			$.ajax({
    				url: url,
    				type : 'post',
    				data : data,
                    cache: false,
                    beforeSend:  function() {
                        $('.loading-shipping-address').show();
                        $('.shipping-step-content').css('opacity','0.2');
                    },
    				success : function(data) {
    				    //kien
                        $('.loading_image').hide();
                        $('.shipping-step-content').css('opacity','1');
                        var _json = $.parseJSON(data);
                        if(_json.success == false){
                            //Billing
                            if(_json.message_billing_firstname){$('.warning-message-billing-firstname').html(_json.message_billing_firstname);$('.warning-message-billing-firstname').show();}else{$('.warning-message-billing-firstname').hide();}
                            if(_json.message_billing_lastname){$('.warning-message-billing-lastname').html(_json.message_billing_lastname);$('.warning-message-billing-lastname').show();}else{$('.warning-message-billing-lastname').hide();}
                            if(_json.message_billing_email){$('.warning-message-billing-email').html(_json.message_billing_email);$('.warning-message-billing-email').show();}else{$('.warning-message-billing-email').hide();}
                            if(_json.message_billing_country){$('.warning-message-billing-country').html(_json.message_billing_country);$('.warning-message-billing-country').show();}else{$('.warning-message-billing-country').hide();}
                            if(_json.message_billing_city){$('.warning-message-billing-city').html(_json.message_billing_city);$('.warning-message-billing-city').show();}else{$('.warning-message-billing-city').hide();}
                            if(_json.message_billing_region){$('.warning-message-billing-state').html(_json.message_billing_region);$('.warning-message-billing-state').show();}else{$('.warning-message-billing-state').hide();}
                            if(_json.message_billing_telephone){$('.warning-message-billing-phone').html(_json.message_billing_telephone);$('.warning-message-billing-phone').show();}else{$('.warning-message-billing-phone').hide();}
                            if(_json.message_billing_company){$('.warning-message-billing-company').html(_json.message_billing_company);$('.warning-message-billing-company').show();}else{$('.warning-message-billing-company').hide();}
                            if(_json.message_billing_fax){$('.warning-message-billing-fax').html(_json.message_billing_fax);$('.warning-message-billing-fax').show();}else{$('.warning-message-billing-fax').hide();}
                            if(_json.message_billing_zip_post){$('.warning-message-billing-zip').html(_json.message_billing_zip_post);$('.warning-message-billing-zip').show();}else{$('.warning-message-billing-zip').hide();}
                            if(_json.message_billing_address){$('.warning-message-billing-address').html(_json.message_billing_address);$('.warning-message-billing-address').show();}else{$('.warning-message-billing-address').hide();}
                            if(_json.message_billing_tax_vat){$('.warning-message-billing-tax').html(_json.message_billing_tax_vat);$('.warning-message-billing-tax').show();}else{$('.warning-message-billing-tax').hide();}
                            if(_json.message_billing_pass){$('.warning-message-billing-pass').html(_json.message_billing_pass);$('.warning-message-billing-pass').show();}else{$('.warning-message-billing-pass').hide();}
                            if(_json.message_billing_repass){$('.warning-message-billing-repass').html(_json.message_billing_repass);$('.warning-message-billing-repass').show();}else{$('.warning-message-billing-repass').hide();}
                            //Shipping
                            if(_json.message_shipping_firstname){$('.warning-message-shipping-firstname').html(_json.message_shipping_firstname);$('.warning-message-shipping-firstname').show();}else{$('.warning-message-shipping-firstname').hide();}
                            if(_json.message_shipping_lastname){$('.warning-message-shipping-lastname').html(_json.message_shipping_lastname);$('.warning-message-shipping-lastname').show();}else{$('.warning-message-shipping-lastname').hide();}
                            if(_json.message_shipping_country){$('.warning-message-shipping-country').html(_json.message_shipping_country);$('.warning-message-shipping-country').show();}else{$('.warning-message-shipping-country').hide();}
                            if(_json.message_shipping_city){$('.warning-message-shipping-city').html(_json.message_shipping_city);$('.warning-message-shipping-city').show();}else{$('.warning-message-shipping-city').hide();}
                            if(_json.message_shipping_region){$('.warning-message-shipping-state').html(_json.message_shipping_region);$('.warning-message-shipping-state').show();}else{$('.warning-message-shipping-state').hide();}
                            if(_json.message_shipping_telephone){$('.warning-message-shipping-phone').html(_json.message_shipping_telephone);$('.warning-message-shipping-phone').show();}else{$('.warning-message-shipping-phone').hide();}
                            if(_json.message_shipping_company){$('.warning-message-shipping-company').html(_json.message_shipping_company);$('.warning-message-shipping-company').show();}else{$('.warning-message-shipping-company').hide();}
                            if(_json.message_shipping_fax){$('.warning-message-shipping-fax').html(_json.message_shipping_fax);$('.warning-message-shipping-fax').show();}else{$('.warning-message-shipping-fax').hide();}
                            if(_json.message_shipping_zip_post){$('.warning-message-shipping-zip').html(_json.message_shipping_zip_post);$('.warning-message-shipping-zip').show();}else{$('.warning-message-shipping-zip').hide();}
                            if(_json.message_shipping_address){$('.warning-message-shipping-address').html(_json.message_shipping_address);$('.warning-message-shipping-address').show();}else{$('.warning-message-shipping-address').hide();}
                            if(_json.message_shipping_tax_vat){$('.warning-message-shipping-tax').html(_json.message_shipping_tax_vat);$('.warning-message-shipping-tax').show();}else{$('.warning-message-shipping-tax').hide();}
                        }else{
                            //david
                            $('.offscreen').addClass('step3');
                            $('.goto-review-step').hide();                                                        
                            //kien                            
                            $('.warning-message').hide();
                            $('.review-step-shipping').html(_json.shipping_method);                        
                            $('.review-step-payment').html(_json.payment_method);
                            $('.review-step-review').html(_json.review_order);
                        }
    				}
    			});
            });
            //ajax saveorder
            shippingForm.submit = function(button, url) {
        		if(this.validator.validate()){
        			var e = null;
        			var data = $('#offcanvas-checkout').serialize();
        			data += '&isAjax=1';
                    url = $('#mst-address-request').val()+'fancycheckout/offcanvascheckout/saveorder';
        			try{
            			$.ajax({
            				url: url,
            				type : 'post',
            				data : data,
                            cache: false,
                            beforeSend:  function() {
                                $('.loading-review').show();
                                if($(window).width()<651){
                                    $('.cart-step-content').css('opacity','0.2');
                                    $('.shipping-step-content').css('opacity','0.2');
                                    $('.review-step').css('opacity','0.2');
                                }else{
                                    $('.review-step').css('opacity','0.2');
                                }
                            },
            				success : function(data) {
            				    $('.loading_image').hide();
                                $('.cart-step-content').css('opacity','1');
                                $('.shipping-step-content').css('opacity','1');
                                $('.review-step').css('opacity','1');
                                var _json = $.parseJSON(data);
                                if(_json.success == false)
                                {
                                    alert(_json.error_messages);
                                }else{
                                    $('#offcanvas-checkout').attr('action',_json.redirect);
                                    $('#offcanvas-checkout').submit();
                                }
            				}
                    	});
        			}catch(e){}
        			if(e){throw e;}
        		}
        	}.bind(shippingForm);
        });
    </script>
<?php } ?>