<div id="checkout-review" class="fancycheckout_block">
    <div class="opc_review_content">
        <div class="other">
            <div class="offcanvascheckout-totals">   
                <?php echo $this->getChildHtml('totals') ?>
            </div>
            <div class="offcanvascheckout-other">
                <?php echo $this->getChildHtml('coupon') ?>
                <?php echo $this->getChildHtml('comment') ?>
                <?php echo $this->getChildHtml('suvery') ?>
                <?php echo $this->getChildHtml('tem_condition') ?>
                <div style="clear: both;"></div>
            </div>
            <div style="clear: both;"></div>
        </div>
    </div>
</div>
