<?php
/**
 * Innoexts
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the InnoExts Commercial License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://innoexts.com/commercial-license-agreement
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@innoexts.com so we can send you a copy immediately.
 * 
 * @category    Innoexts
 * @package     Innoexts_CurrencyPricing
 * @copyright   Copyright (c) 2014 Innoexts (http://www.innoexts.com)
 * @license     http://innoexts.com/commercial-license-agreement  InnoExts Commercial License
 */
?>
<?php $helper = Mage::helper('currencypricing') ?>

<script type="text/javascript">

//<![CDATA[
function hideShowSubproductOptions()
{
    if ($('rule_sub_is_enable').value == 1) {
        $('rule_sub_simple_action').up('tr').show();
        $('rule_sub_discount_amount').up('tr').show();
        $('rule_sub_discount_amount').addClassName('required-entry validate-not-negative-number');
        $('rule_compound_sub_discount_amounts_control').up('tr').show();
    } else {
        $('rule_sub_simple_action').up('tr').hide();
        $('rule_sub_discount_amount').up('tr').hide();
        $('rule_sub_discount_amount').removeClassName('required-entry').removeClassName('validate-not-negative-number');
        $('rule_compound_sub_discount_amounts_control').up('tr').hide();
    }

    return true;
}

document.observe("dom:loaded", hideShowSubproductOptions);
//]]>
</script>
