<?php if ($_item = $this->getItem()): ?>
    <h5 class="title"><?php echo $this->htmlEscape($_item->getName()) ?></h5>
    <div><strong><?php echo $this->helper('sales')->__('SKU') ?>:</strong> <?php echo implode('<br />', Mage::helper('catalog')->splitSku($this->htmlEscape($this->getSku()))); ?></div>
        <dl class="item-options">
        <?php foreach ($this->getOrderOptions() as $_option): ?>
            <dt><?php echo $_option['label'] ?></dt>
            <dd>
            <?php if (isset($_option['custom_view']) && $_option['custom_view']): ?>
                <?php echo $this->getCustomizedOptionValue($_option); ?>
            <?php else:
					$_prepend=''; $_append='';
					if(preg_match('/^https?:/i',$_option['value'])){
						$_prepend='<a target="_new" href="'.$this->htmlEscape($_option['value']).'">'; $_append='</a>';
					}
	    ?>
                <?php echo $_prepend.Mage::helper('core/string')->truncate($_option['value'], 55, '', $_remainder).$_append;?>
                <?php if ($_remainder):?>
                    ... <span id="<?php echo $_id = 'id' . uniqid()?>"><?php echo $_remainder ?></span>
                    <script type="text/javascript">
                    $('<?php echo $_id ?>').hide();
                    $('<?php echo $_id ?>').up().observe('mouseover', function(){$('<?php echo $_id ?>').show();});
                    $('<?php echo $_id ?>').up().observe('mouseout',  function(){$('<?php echo $_id ?>').hide();});
                    </script>
                <?php endif;?>
            <?php endif;?>
            </dd>
        <?php endforeach; ?>
        </dl>
    <?php echo $this->htmlEscape($_item->getDescription()) ?>
<?php endif; ?>
