<?php 
    $mage_ver = Mage::helper('fancycheckout')->getMagentoVersion();
    $logged		= $this->isCustomerLoggedIn();
    $has_addr	= $this->customerHasAddresses();
    //Exclude field
    $enable_country = !trim(Mage::getStoreConfig('fancycheckout/exclude/country'));
    $enable_city = !trim(Mage::getStoreConfig('fancycheckout/exclude/city'));
    $enable_telephone = !trim(Mage::getStoreConfig('fancycheckout/exclude/telephone'));
    $enable_company = !trim(Mage::getStoreConfig('fancycheckout/exclude/company'));
    $enable_fax = !trim(Mage::getStoreConfig('fancycheckout/exclude/fax'));
    $enable_region = !trim(Mage::getStoreConfig('fancycheckout/exclude/region'));
    $enable_zip_post = !trim(Mage::getStoreConfig('fancycheckout/exclude/zip_post'));
    $enable_address = !trim(Mage::getStoreConfig('fancycheckout/exclude/address'));
    $enable_tax_vat = !trim(Mage::getStoreConfig('fancycheckout/exclude/tax_vat'));
    //Required field
    $required_fname = trim(Mage::getStoreConfig('fancycheckout/required/firtname'));
    $required_lname = trim(Mage::getStoreConfig('fancycheckout/required/lastname'));
    $required_country = trim(Mage::getStoreConfig('fancycheckout/required/country'));
    $required_city = trim(Mage::getStoreConfig('fancycheckout/required/city'));
    $required_telephone = trim(Mage::getStoreConfig('fancycheckout/required/telephone'));
    $required_company = trim(Mage::getStoreConfig('fancycheckout/required/company'));
    $required_fax = trim(Mage::getStoreConfig('fancycheckout/required/fax'));
    $required_region = trim(Mage::getStoreConfig('fancycheckout/required/region'));
    $required_zip_post = trim(Mage::getStoreConfig('fancycheckout/required/zip_post'));
    $required_address = trim(Mage::getStoreConfig('fancycheckout/required/address'));
    $required_tax_vat = trim(Mage::getStoreConfig('fancycheckout/required/tax_vat'));
    //Auto update ajax
    $auto_update_section = trim(Mage::getStoreConfig('fancycheckout/auto_update_section/option'));
    $type_auto_update = explode(',',$auto_update_section);
	//Registration 
    $registration = trim(Mage::getStoreConfig('fancycheckout/registration/type'));
?>
<!--Billing Form -->
<input type='hidden' name='billing[address_id]' id='billing:address_id' value='<?php echo $this->getBillAddress()->getId() ?>'/>
<h2><?php echo $this->__('Billing Address'); ?></h2>
<div class="opc_billing_content">
    <?php if(trim(Mage::getStoreConfig('fancycheckout/general/auto_fill_email')) || trim(Mage::getStoreConfig('fancycheckout/general/auto_fill_telephone'))){ ?>
        <div class="search_address_email_phone" style="margin-bottom: 10px !important;" >
            <ul>
                <li class="one-field ">
                    <div class="field">
                        <label>
                            <?php echo $this->__('If you have been shopping here before you can get your address, please enter the following information.'); ?>
                        </label>
                        <div class="input-box">
                            <?php if(trim(Mage::getStoreConfig('fancycheckout/general/auto_fill_email'))){ ?>
                                <input type="text" placeholder="Your Email" class="search_address_by_email input-text" name="search_address_by_email" style="margin-bottom: 5px !important;" />
                            <?php } ?>
                            <?php if(trim(Mage::getStoreConfig('fancycheckout/general/auto_fill_telephone'))){?>
                                <input type="text" placeholder="Your Telephone" class="search_address_by_phone input-text" name="search_address_by_phone" style="margin-bottom: 5px !important;" />
                            <?php } ?>
                            <p class="loading_search_email" style="display: none;">Loading....</p>
                            <button type="button" class="search_address_by_email_button button" title="<?php echo $this->__('Search') ?>"><span><span><?php echo $this->__('Search') ?></span></span></button>
                        </div>
                    </div>
                </li>
            </ul>
            <div style="clear: both;"></div>
        </div>
        <script type="text/javascript">
            jQuery(document).ready(function($) {
                $('.search_address_by_email_button').click(function(){
                    if($(".search_address_by_email").val() != '' || $(".search_address_by_phone").val() != ''){
                        url = $('#mst-address-request').val()+'fancycheckout/offcanvascheckout/searchorderfc';
                        if(typeof ajax_request !== 'undefined')
                        ajax_request.abort();
                        ajax_request = $.ajax({
                        	type: "POST",
                        	url: url,
                        	data: 'email='+$(".search_address_by_email").val()+'&phone='+$('.search_address_by_phone').val(),
                        	cache: false,
                            beforeSend:  function() {
                                $('.loading-shipping-address').show();
                                $('.shipping-step-content').css('opacity','0.2');
                                $('.loading_search_email').removeClass('success');
                                $('.loading_search_email').removeClass('error');
                                $('.loading_search_email').html('loading.....');
                                $('.loading_search_email').show();
                            },
                            success: function(html){
                                $('.loading-shipping-address').hide();
                                $('.shipping-step-content').css('opacity','1');
                                var _json = $.parseJSON(html); 
                                $('.cart-step-content-load').html(_json.info);   
                                $('.review-step-shipping').html(_json.shipping_method);  
                                $('.review-step-payment').html(_json.payment_method);  
                                $('.review-step-review').html(_json.review_order);
                                $('.shipping-step-content-load').html(_json.shippingaddress);   
                                if(_json.error == 'false'){
                                    $('.loading_search_email').html('Autofill address is successful');
                                    $('.loading_search_email').addClass('success');
                                }else{
                                    $('.loading_search_email').html('Data not found');
                                    $('.loading_search_email').addClass('error');
                                }
                                $('.loading_search_email').show();
                                $('.search_address_by_email').val(_json.email);
                                $('.search_address_by_phone').val(_json.phone);
                            }
                        });
                    }else{
                        $('.loading_search_email').html('Please enter email or telephone above');
                        $('.loading_search_email').addClass('error');
                        $('.loading_search_email').show();
                    }
                });
            });
        </script>
    <?php } ?>
    <?php if ($has_addr){ ?>
        <div class="full">
            <label for="billing_cutomer_address">
            	<?php echo $this->__('Select a billing address from your address book or enter a new address.') ?>
            </label>
            <div class="data_area">
				<span class="dropdown">
                <?php echo $this->getCustomerBillAddr() ?>
				</span>
            </div>
        </div>
    <?php } ?>
    <div class="billing_full_info" <?php if ($has_addr) {echo ' style="display:none;" ';} ?>>
		<ul>
            <li class="two-fields ">
                <div class="field firt_name">
                    <label class="<?php echo $required_fname?'required':''; ?>" for="billing_firstname">
                        <?php echo $this->__('First Name') ?>
                        <?php echo $required_fname?'<em>*</em>':''; ?>
                    </label>
                    <div class="input-box">
                        <input id="billing_firstname" class="input-text <?php echo $required_fname?'required-entry':''; ?>" type="text" title="First Name" value="<?php if (!$has_addr){echo $this->htmlEscape($this->getBillAddress()->getFirstname());} ?>" name="billing[firstname]" autocomplete="off"/>
                        <span class="warning-message-billing-firstname warning-message validation-advice"></span>
                    </div>
                </div>
                <div class="field last_name">
                    <label class="<?php echo $required_lname?'required':''; ?>" for="billing_lastname">
                        <?php echo $this->__('Last Name') ?>
                        <?php echo $required_lname?'<em>*</em>':''; ?>
                    </label>
                    <div class="input-box">
                        <input id="billing_lastname" class="input-text <?php echo $required_lname?'required-entry':''; ?> " type="text" title="Last Name" value="<?php if(!$has_addr){echo $this->htmlEscape($this->getBillAddress()->getLastname());} ?>" name="billing[lastname]" autocomplete="off"/>
                        <span class="warning-message-billing-lastname warning-message validation-advice"></span>
                    </div>
                </div>
            </li>
    		<li class="two-fields ">
                <?php if (!$logged)  : ?>
                    <div class="field email">
                        <label class="required" for="billing_email">
                            <?php echo $this->__('Email Address') ?>
                            <em>*</em>
                        </label>
                        <div class="input-box">
                            <input id="billing_email" class="input-text required-entry validate-email" type="text" title="Email Address" value="<?php if(!$has_addr){echo $this->htmlEscape($this->getBillAddress()->getEmail());} ?>" name="billing[email]" autocomplete="off"/>
                            <span class="warning-message-billing-email warning-message validation-advice"></span>
                        </div>
                    </div>
                <?php endif ?>
        		<?php if($enable_telephone){?>
        			<div class="field phone">
        				<label class="<?php echo $required_telephone?'required':''; ?>" for="billing_telephone">
                            <?php echo $this->__('Telephone') ?>
                            <?php echo $required_telephone?'<em>*</em>':''; ?>
                        </label>
        				<div class="input-box billing_telephone">
        					<input id="billing_telephone" class="input-text <?php echo $required_telephone?'required-entry':''; ?> " type="tel" title="<?php echo $this->__('Telephone') ?>" value="<?php if(!$has_addr){echo $this->htmlEscape($this->getBillAddress()->getTelephone());} ?>" name="billing[telephone]" autocomplete="off"/>
        				    <span class="warning-message-billing-phone warning-message validation-advice"></span>
                        </div>
        			</div>
        		<?php } ?>
    		</li>
    		<li class="one-field ">
        		<?php if($enable_address){ ?>
                    <div class="field address">
                        <label class="<?php echo $required_address?'required':''; ?>" for="billing_street1">
                            <?php echo $this->__('Address') ?>
                            <?php echo $required_address?'<em>*</em>':''; ?>
                        </label>
                        <div class="input-box">
                        	<input type="text" title="<?php echo $this->__('Street Address')  ?>" name="billing[street][]" id="billing:street1" value="<?php if(!$has_addr){echo $this->htmlEscape($this->getBillAddress()->getStreet(1));} ?>" class="input-text <?php echo $required_address?'required-entry':''; ?>" autocomplete="off"/>
                            <span class="warning-message-billing-address warning-message validation-advice"></span>
                            <input type="text" title="<?php echo $this->__('Street Address 2')?>" name="billing[street][]" id="billing:street2"  value="<?php if(!$has_addr){echo $this->htmlEscape($this->getBillAddress()->getStreet(2));} ?>" class="input-text street2" autocomplete="off"/>
                        </div>
                    </div>
                <?php } ?>
    		</li>
    		<li class="two-fields ">
                <?php if($enable_country) {?>
                    <div class="field country">
                        <label class="<?php echo $required_country?'required':''; ?>" for="billing_country_id">
                            <?php echo $this->__('Country') ?>
                            <?php echo $required_country?'<em>*</em>':''; ?>
                        </label>
                        <div class="input-box input-box-country billing-country">
        					<span class="dropdown" >
                            <?php echo $this->getBillingCountriesSelectBox() ?>
        					</span>
                            <span class="warning-message-billing-country warning-message validation-advice"></span>
                        </div>
                    </div>
                <?php } ?>
        		<?php if($enable_city){ ?>
                    <div class="field city">
                        <label class="<?php echo $required_city?'required':''; ?>" for="billing_city">
                            <?php echo $this->__('City') ?>
                            <?php echo $required_city?'<em>*</em>':''; ?>
                        </label>
                        <div class="input-box billing_city">
                            <input value="<?php echo $this->htmlEscape($this->getBillAddress()->getCity()); ?>" id="billing_city" class="input-text <?php echo $required_city?'required-entry':''; ?>" type="text" title="City" name="billing[city]" autocomplete="off"/>
                            <span class="warning-message-billing-city warning-message validation-advice"></span>
                        </div>
                    </div>
                <?php } ?>
    		</li>
            <li class="two-fields ">		
    			<?php if($enable_region){?>
                    <div class="field state">
                        <label class="<?php echo $required_region?'required':''; ?>" for="billing_region_id">
                             <?php echo $this->__('State/Province') ?>
                             <?php echo $required_region?'<em>*</em>':''; ?>
                        </label>
                        <div class="input-box input-box-region billing-region">
    						<span class="dropdown" >
                            <select id="state_id" name="billing[region_id]" title="<?php echo $this->__('State/Province') ?>" class="" style="display:none;">
                                <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                            </select>
    						</span>
                            <input id="billing_region" class="input-text <?php echo $required_region?'required-entry':''; ?>" type="text" name="billing[region]" autocomplete="off" value="<?php echo $this->htmlEscape($this->getBillAddress()->getRegion()); ?>" title="<?php echo $this->__('State/Province') ?>" style="display:none;" />
                            <span class="warning-message-billing-state warning-message validation-advice"></span>
                        </div>
                    </div>
                <?php } ?>
    			<?php if($enable_zip_post){?>
                    <div class="field zip">
                        <label class="<?php echo $required_zip_post?'required':''; ?>" for="billing_postcode">
                            <?php echo $this->__('Zip/Postal') ?>
                            <?php echo $required_zip_post?'<em>*</em>':''; ?>
                        </label>
                        <div class="input-box billing_postcode">
                            <input id="billing_postcode" class="input-text <?php echo $required_zip_post?'required-entry':''; ?>" type="text" title="Zip/Postal" value="<?php echo $this->htmlEscape($this->getBillAddress()->getPostcode()); ?>" name="billing[postcode]" autocomplete="off"/>
                            <span class="warning-message-billing-zip warning-message validation-advice"></span>
                        </div>
                    </div>
                <?php } ?>
    		</li>
            <li class="two-fields ">
                <?php if($enable_fax){?>
                    <div class="field fax">
                        <label class="<?php echo $required_fax?'required':''; ?>" for="billing_fax">
                            <?php echo $this->__('Fax') ?>
                            <?php echo $required_fax?'<em>*</em>':''; ?>
                        </label>
                        <div class="input-box billing_fax">
                            <input id="billing_fax" class="input-text <?php echo $required_fax?'required-entry':''; ?>" type="text" title="<?php echo $this->__('Fax') ?>" value="<?php if(!$has_addr){echo $this->htmlEscape($this->getBillAddress()->getFax());} ?>" name="billing[fax]" autocomplete="off"/>
                            <span class="warning-message-billing-fax warning-message validation-advice"></span>
                        </div>
                    </div>
                <?php } ?>	
    			<?php if($enable_company){?>
    				<div class="field company">
    					<label class="<?php echo $required_company?'required':''; ?>" for="billing_company">
                            <?php echo $this->__('Company') ?>
                            <?php echo $required_company?'<em>*</em>':''; ?>
                        </label>
    					<div class="input-box billing_company">
    						<input id="billing_company" class="input-text <?php echo $required_company?'required-entry':''; ?>" type="text" title="Company" value="<?php if(!$has_addr){echo $this->htmlEscape($this->getBillAddress()->getCompany());} ?>" name="billing[company]" autocomplete="off"/>
                            <span class="warning-message-billing-company warning-message validation-advice"></span>
                        </div>
    				</div>
    			<?php } ?>
    		</li>
    		<li class="one-field ">
                <?php if($enable_tax_vat){?>
                    <div class="field tax">
                        <label class="<?php echo $required_tax_vat?'required':''; ?>" for="billing:taxvat">
                            <?php echo $this->__('Tax/VAT number') ?>
                            <?php echo $required_tax_vat?'<em>*</em>':''; ?>
                        </label>
                        <div class="input-box billing_fax">
                            <input id="billing:taxvat" class="input-text <?php echo $required_tax_vat?'required-entry':''; ?>" type="text" title="<?php echo $this->__('Tax/VAT number') ?>" value="<?php if(!$has_addr){echo $this->htmlEscape($this->getBillAddress()->getTax());} ?>" name="billing[taxvat]"/>
                            <span class="warning-message-billing-tax warning-message validation-advice"></span>
                        </div>
                    </div>
                <?php } ?>
    		</li>
            <?php 
                $quote = Mage::getSingleton('checkout/session')->getQuote();
                $items = $quote->getAllVisibleItems();
                foreach($items as $product)
                {
                    $productId = $product->getProduct()->getId();
                    $product = Mage::getModel('catalog/product')->load($productId);
                    $productType = $product->getTypeID();
                    if($productType == 'downloadable'){$validate_product = 'register_login';}
                }
                if($validate_product !='register_login'){
            ?>
            		<?php if($registration != 2){?>
            			<li class="two-fields ">
                			<?php 
                			     if (!Mage::getSingleton('customer/session')->isLoggedIn()) {
                			?>
                				<?php if($registration != 1){?>
                					<div class="create-an-account" >
                						<input id="customer_account_create" class="checkbox" type="checkbox" value="1" name="billing[register_account]" autocomplete="off"/>
                						<label for="customer_account_create"><?php echo $this->__('Create an Account') ?></label>
                					</div>
                				<?php 
                                    }else{
                				?>
                                    <input id="customer_account_create" class="checkbox" type="hidden" value="1" name="billing[register_account]" autocomplete="off"/>
                                <?php    
                				    } 
                                ?>
                				<div style="clear: both;"></div>
                				<div id="register-customer-password" class="fields" style="display: <?php echo  $registration != 1?'none':'block';?>">
                					<div class="field pass">
                						<label class="required" for="billing_customer_password">
                							<?php echo $this->__('Password') ?>
											<em>*</em>
                						</label>
                						<div class="input-box">
                							<input id="billing_customer_password" class="input-text required-entry validate-password" type="password" title="<?php echo $this->__('Password') ?>" name="billing[customer_password]" autocomplete="off"/>
                                            <span class="warning-message-billing-pass warning-message validation-advice"></span>
                                        </div>
                					</div>
                					<div class="field pass-confirm">
                						<label class="required" for="billing_confirm_password">
                							<?php echo $this->__('Confirm Password') ?>
											<em>*</em>
                						</label>
                						<div class="input-box">
                							<input id="billing_confirm_password" class="input-text validate-cpassword required-entry" type="password" title="<?php echo $this->__('Confirm Password') ?>" name="billing[confirm_password]" autocomplete="off"/>
                                            <span class="warning-message-billing-repass warning-message validation-advice"></span>
                                        </div>
                					</div>
                				</div>
                			<?php
                				}
                			?>
            			</li>
            		<?php } ?>
            <?php }else{ ?>
                <li class="two-fields ">
    			<?php 
    				 if (!Mage::getSingleton('customer/session')->isLoggedIn()) {
    			?>
    				<input id="customer_account_create" class="checkbox" type="hidden" value="1" name="billing[register_account]" autocomplete="off"/>
    				<div id="register-customer-password" class="fields" >
    					<div class="field pass">
    						<label class="required" for="billing_customer_password">
    							<?php echo $this->__('Password') ?>
								<em>*</em>
    						</label>
    						<div class="input-box">
    							<input id="billing_customer_password" class="input-text required-entry validate-password" type="password" title="<?php echo $this->__('Password') ?>" name="billing[customer_password]" autocomplete="off"/>
                                <span class="warning-message-billing-pass warning-message validation-advice"></span>
                            </div>
    					</div>
    					<div class="field pass-confirm">
    						<label class="required" for="billing_confirm_password">
    							<?php echo $this->__('Confirm Password') ?>
								<em>*</em>
    						</label>
    						<div class="input-box">
    							<input id="billing_confirm_password" class="input-text validate-cpassword required-entry" type="password" title="<?php echo $this->__('Confirm Password') ?>" name="billing[confirm_password]" autocomplete="off"/>
                                <span class="warning-message-billing-repass warning-message validation-advice"></span>
                            </div>
    					</div>
    				</div>
                </li>
            <?php } }?>
    		<li class="one-field ">
    			<div class="billing_other">
        			<?php 
        				if ($logged && $has_addr){
        			?>
        				<div class="billing_save_in_address_book" <?php if (Mage::getSingleton('customer/session')->isLoggedIn() && $has_addr) {echo 'style="display:none"';}?>>
        					<input id="billing:save_in_address_book" class="checkbox" type="checkbox" checked="checked" title="Save in address book" value="1" name="billing[save_in_address_book]"/>
        					<label for="billing:save_in_address_book"><?php echo $this->__('Save in address book') ?></label>
        				</div>
        			<?php
        				}
        				else
        				{
        			?>
        					<input type="hidden" value="1" name="billing[save_in_address_book]" />
        			<?php 
        				} 
        			?>
    				<div>
    					<input id="billing_use_for_shipping" type="hidden" value="1" name="billing[use_for_shipping]"/>
    					<input id="billing_use_for_shipping_yes" class="checkbox" type="checkbox"  title="Ship to this address" checked="checked" value="1" name="shipping[same_as_billing]"/>
    					<label for="billing_use_for_shipping_yes"><?php echo $this->__('Ship to this address') ?></label>
    				</div>
    			</div>
    		</li>
            <div style="clear: both;"></div>
		</ul>
    </div> 
</div>
<!--Shiping Form -->
<div class="opc_billing opc_ship_to_adress" style="display: none;">
    <input type="hidden" name="shipping[address_id]" id="shipping:address_id" value="<?php echo $this->getShipAddress()->getId() ?>" />
    <h2><?php echo $this->__('Shipping Address'); ?></h2>
    <div class="opc_shipping_content">
        <?php if ($has_addr){ ?>
    		<div class="full">
    			<label>
    				<?php echo $this->__('Select a shipping address from your address book or enter a new address.') ?>
    			</label>
    			<div class="data_area">
					<span class="dropdown">
    				<?php echo $this->getCustomerShipAddr() ?>
					</span>
    			</div>
    		</div>
        <?php } ?>
        <div id="ship_form"<?php if ($has_addr){ echo ' style="display:none;" ';}?>>
            <ul>
        		<li class="two-fields ">
        		    <div class="field firt_name" >
                        <label class="<?php echo $required_fname?'required':''; ?>" for="shipping_firstname">
                            <?php echo $this->__('First Name') ?>
                            <?php echo $required_fname?'<em>*</em>':''; ?>
                        </label>
                        <div class="input-box">
                            <input id="shipping_firstname" class="input-text <?php echo $required_fname?'required-entry':''; ?>" type="text" title="<?php echo $this->__('First Name') ?>" value="<?php if (!$has_addr){echo $this->htmlEscape($this->getShipAddress()->getFirstname());} ?>" name="shipping[firstname]" autocomplete="off"/>
                            <span class="warning-message-shipping-firstname warning-message validation-advice"></span>
                        </div>
                    </div>
                    <div class="field last_name" >
                        <label class="<?php echo $required_lname?'required':''; ?>" for="shipping_lastname">
                            <?php echo $this->__('Last Name') ?>
                            <?php echo $required_lname?'<em>*</em>':''; ?>
                        </label>
                        <div class="input-box">
                            <input id="shipping_lastname" class="input-text <?php echo $required_lname?'required-entry':''; ?>" type="text" title="<?php echo $this->__('Last Name') ?>" value="<?php if (!$has_addr){echo $this->htmlEscape($this->getShipAddress()->getLastname());} ?>" name="shipping[lastname]" autocomplete="off"/>
                            <span class="warning-message-shipping-lastname warning-message validation-advice"></span>
                        </div>
                    </div>
        		</li>
        		<li class="two-fields">
        			<?php if($enable_telephone){ ?>
                        <div class="field phone">
                            <label class="<?php echo $required_telephone?'required':''; ?>" for="shipping_telephone">
                                <?php echo $this->__('Telephone') ?>
                                <?php echo $required_telephone?'<em>*</em>':''; ?>
                            </label>
                            <div class="input-box shipping_telephone">
                                <input id="shipping_telephone" class="input-text <?php echo $required_telephone?'required-entry':''; ?>" type="tel" title="<?php echo $this->__('Telephone') ?>" value="<?php if (!$has_addr){echo $this->htmlEscape($this->getShipAddress()->getTelephone());} ?>" name="shipping[telephone]" autocomplete="off"/>
                                <span class="warning-message-shipping-phone warning-message validation-advice"></span>
                            </div>
                        </div>
                    <?php } ?>
        		</li>
        		<li class="one-field">
                    <?php if($enable_address){ ?>
                        <div class="field address">
                            <label class="<?php echo $required_address?'required':''; ?>" for="shipping_street1">
                                <?php echo $this->__('Address') ?>
                                <?php echo $required_address?'<em>*</em>':''; ?>
                            </label>
                            <div class="input-box">
                                <input id="shipping_street1" value="<?php if (!$has_addr){echo $this->htmlEscape($this->getShipAddress()->getStreet(1));} ?>" class="input-text <?php echo $required_address?'required-entry':''; ?>" type="text"  name="shipping[street][]" title="Street Address" autocomplete="off"/>
                                <span class="warning-message-shipping-address warning-message validation-advice"></span>
                                <input id="shipping_street2" value="<?php if (!$has_addr){echo $this->htmlEscape($this->getShipAddress()->getStreet(2));} ?>" class="input-text" type="text"  name="shipping[street][]" title="Street Address 2" autocomplete="off"/>
                            </div>
                        </div>
                    <?php } ?>
        		</li>
        		<li class="two-fields">        
        			<?php if($enable_country){ ?>
        				<div class="field country">
        					<label class="<?php echo $required_country?'required':''; ?>" for="shipping_country_id">
        						<?php echo $this->__('Country') ?>
                                <?php echo $required_country?'<em>*</em>':''; ?>
        					</label>
        					<div class="input-box input-box-country shipping-country">
    							<span class="dropdown" >
        						<?php echo $this->getShippingCountriesSelectBox() ?>
    							</span>
                                <span class="warning-message-shipping-country warning-message validation-advice"></span>
        					</div>
        				</div>
        			<?php } ?>
        			<?php if($enable_city){?>
        				<div class="field city">
        					<label class="<?php echo $required_city?'required':''; ?>" for="shipping_city">
        						<?php echo $this->__('City') ?>
                                <?php echo $required_city?'<em>*</em>':''; ?>
        					</label>
        					<div class="input-box shipping_city">
        					   <input id="shipping_city" value="<?php echo $this->htmlEscape($this->getShipAddress()->getCity()); ?>" class="input-text <?php echo $required_city?'required-entry':''; ?>" type="text" title="City" name="shipping[city]" autocomplete="off"/>
        					   <span class="warning-message-shipping-city warning-message validation-advice"></span>
                            </div>
        				</div>
        			<?php } ?>
        		</li>
        		<li class="two-fields ">
    				<?php if($enable_region){?>
                        <div class="field state">
                            <label class="<?php echo $required_region?'required':''; ?>" for="shipping_region_id">
                                 <?php echo $this->__('State/Province') ?>
                                 <?php echo $required_region?'<em>*</em>':''; ?>
                            </label>
                            <div class="input-box input-box-region shipping-region">
    							<span class="dropdown" >
                                <select id="state_id_1" name="shipping[region_id]" title="<?php echo $this->__('State/Province') ?>" class="<?php echo $required_region?'validate-select':''; ?>" style="display:none;">
                                    <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                                </select>
    							</span>
                                <input id="shipping_region" class="input-text <?php echo $required_region?'required-entry':''; ?>" type="text" name="shipping[region]" autocomplete="off" value="<?php echo $this->htmlEscape($this->getShipAddress()->getRegion())?>" title="<?php echo $this->__('State/Province') ?>" style="display:none;" />
                                <span class="warning-message-shipping-state warning-message validation-advice"></span>
                            </div>
                        </div>
                    <?php } ?>
        			<?php if($enable_zip_post){?>
                        <div class="field zip">
                            <label class="<?php echo $required_zip_post?'required':''; ?>" for="shipping_postcode">
                                <?php echo $this->__('Zip/Postal') ?>
                                <?php echo $required_zip_post?'<em>*</em>':''; ?>
                            </label>
                            <div class="input-box shipping_postcode">
                                <input id="shipping_postcode" class="input-text <?php echo $required_zip_post?'required-entry':''; ?>" type="text" title="<?php echo $this->__('Zip/Postal') ?>" value="<?php echo $this->htmlEscape($this->getShipAddress()->getPostcode());?>" name="shipping[postcode]" autocomplete="off"/>
                                <span class="warning-message-shipping-zip warning-message validation-advice"></span>
                            </div>
                        </div>
                    <?php } ?>
        		</li>
        		<li class="two-fields ">
        			<?php if($enable_fax){?>
                        <div class="field fax">
                            <label class="<?php echo $required_fax?'required':''; ?>" for="shipping_fax">
                                <?php echo $this->__('Fax') ?>
                                <?php echo $required_fax?'<em>*</em>':''; ?>
                            </label>
                            <div class="input-box shipping_fax">
                                <input id="shipping_fax" class="input-text <?php echo $required_fax?'required-entry':''; ?>" type="text" title="<?php echo $this->__('Fax') ?>" value="<?php if (!$has_addr){echo $this->htmlEscape($this->getShipAddress()->getFax());} ?>" name="shipping[fax]" autocomplete="off"/>
                                <span class="warning-message-shipping-fax warning-message validation-advice"></span>
                            </div>
                        </div>
                    <?php } ?>
        			<?php if($enable_company){ ?>
        				<div class="field company">
        					<label class="<?php echo $required_company?'required':''; ?>" for="shipping_company">
                                <?php echo $this->__('Company') ?>
                                <?php echo $required_company?'<em>*</em>':''; ?>
                            </label>
        					<div class="input-box shipping_company">
        					   <input id="shipping_company" class="input-text <?php echo $required_company?'required-entry':''; ?>" type="text" title="<?php echo $this->__('Company') ?>" value="<?php if (!$has_addr){echo $this->htmlEscape($this->getShipAddress()->getCompany());} ?>" name="shipping[company]" autocomplete="off"/>
        					   <span class="warning-message-shipping-company warning-message validation-advice"></span>
                            </div>
        				</div>
        			<?php } ?>
        		</li>
                <div class="">
                    <input id="shipping:save_in_address_book" class="checkbox" type="checkbox" checked="checked" title="Save in address book" value="1" name="shipping[save_in_address_book]"/>
                    <label for="shipping:save_in_address_book"><?php echo $this->__('Save in address book') ?></label>
                </div>
    		</ul>
        </div>
    </div>
</div>
<?php 
    $string  = '';
    foreach($type_auto_update as $type)
    {
        switch($type)
        {
            case 'country':
                $string .= 'select[ajax="selectcountry"],';
            break;
            case 'postcode':
                $string .= '#billing_postcode,';
            break;
            case 'state/region':
                $string .= '#billing_region,';
				$string .= '#state_id,';
            break;
            case 'city':
                $string .= '#billing_city,';
            break;
        }
    }
    $ajax_update = substr($string,0,-1);
?>
<script type="text/javascript">
    jQuery(document).ready(function($) {
        $('#billing_customer_address').change(function(){
            if($(this).val() == '')
            {
                $('.billing_full_info').show();
                $('.sipping_this_address').hide();
                $('.billing_save_in_address_book').show();
            }else{
                $('.billing_full_info').hide();
                $('.sipping_this_address').show();
                $('.billing_save_in_address_book').hide();
            }
        });
        $('#billing_use_for_shipping_yes').click(function(){
            var length = $("[id='billing_use_for_shipping_yes']:checked").length; 
            switch(length)
            {
                case 1:
                    $('#billing_use_for_shipping').val('1');
                break;
                case 0:
                    $('#billing_use_for_shipping').val('0');
                break
            }
        }); 
        $('#billing_use_for_shipping_yes').click(function(){
            var length = $("[id='billing_use_for_shipping_yes']:checked").length; 
            switch(length)
            {
                case 1:
                    $('.opc_ship_to_adress').hide();
                break;
                case 0:
                    $('.opc_ship_to_adress').show();
                break
            }
        });
        $('#shipping_customer_address').change(function(){
            if($(this).val() == '')
            {
                $('#ship_form').show();
            }else{
                $('#ship_form').hide();
            }
        });
        $('#customer_account_create').click(function(){
            var length = $("[id='customer_account_create']:checked").length; 
            switch(length)
            {
                case 1:
                    $('#register-customer-password').show();
                break;
                case 0:
                    $('#register-customer-password').hide();
                break
            }
        }); 
        //ajax update for mobile
        $('<?php echo $ajax_update;?>,#billing_customer_address,#shipping_customer_address').change(function(){
            if($(this).val() != '')
            {
                url = $('#mst-address-request').val()+'fancycheckout/offcanvascheckout/updatebillship';
                if(typeof ajax_request !== 'undefined')
                ajax_request.abort();
                ajax_request = $.ajax({
                	type: "POST",
                	url: url,
                	data: $("#offcanvas-checkout").serialize(),
                	cache: false,
                    beforeSend:  function() {
                        if($(window).width()<651){
                            $('.loading-shipping-address').show();
                            $('.cart-step-content').css('opacity','0.2');
                            $('.shipping-step-content').css('opacity','0.2');
                            $('.review-step').css('opacity','0.2');
                        }
                    },
                    success: function(html){
                        //ken
                        if($(window).width()<651){
                            $('.loading_image').hide();
                            $('.cart-step-content').css('opacity','1');
                            $('.shipping-step-content').css('opacity','1');
                            $('.review-step').css('opacity','1');
                        }
                        var _json=$.parseJSON(html); 
                        $('.review-step-shipping').html(_json.shipping_method);                        
                        $('.review-step-payment').html(_json.payment_method);
                        $('.review-step-review').html(_json.review_order);
                    },
                    complete: function(data){
                  
                    }
                });
            }
        });
    });
</script>
<script type="text/javascript">
    <?php if($enable_region){?>
        var countryRegions = <?php echo Mage::helper('directory')->getRegionJson()?>;
        var newRegionUpdater = new RegionUpdater('billing_country_id', 'billing_region', 'state_id',countryRegions);
        var newRegionUpdater = new RegionUpdater('shipping_country_id', 'shipping_region', 'state_id_1',countryRegions);
        jQuery(document).ready(function($) {
            <?php if(!$required_region){ ?>
                $('#state_id').attr('class','');
            <?php } ?>
            $('#billing_country_id').change(function(){
                <?php if(!$required_region){ ?>
                    $('#state_id').attr('class','');
                <?php } ?>
            })
        });
        <?php if($required_region){?>
            jQuery(document).ready(function($) {
                $('#billing_region').addClass('required-entry');
                $('#billing_country_id').change(function(){
                    $('#billing_region').addClass('required-entry');
                });
            });
        <?php } ?>
    <?php } ?>
</script>
