<!doctype html>
<title>MagicYourBand.com Maintenance mode</title>
<style>
  body { text-align: center; padding: 150px; }
  h1 { font-size: 50px; }
  body { font: 20px Helvetica, sans-serif; color: #333; }
  article { display: block; text-align: center; width: 650px; margin: 0 auto; }
  a { color: #dc8100; text-decoration: none; }
  a:hover { color: #333; text-decoration: none; }
</style>
 
<article>
    <h1>We'll be back soon!</h1>
    <div>
        <p>Sorry for the inconvenience, but due to our increased order volume magicyourband.com is currently moving to a new server. If you are seeing this then you have already reached our new server and the site will be back up and running very soon! In the meantime if you need to you can always <a href="mailto:tracy@magicyourband.com">contact us</a>, otherwise check back again shortly!</p>
        
        <p>&mdash; Magic Your Band</p>
        <img src="https://www.magicyourband.com/skin/frontend/default/theme227k/images/logo.gif" class="logo-image" alt="MagicYourBand">
 
    </div>
</article>