<div class="full-width-container">
<div class="page-title category-title">
        <h1>Customer Designs In the Showcase</h1>
</div>

<?php 
$showcaseCollection = Mage::getModel('showcase/showcase')->getCollection()->addFieldToFilter('is_active',1)->setOrder('created_at', 'desc');
$count=0;
?>
<ul class="products-grid row odd">
<?php foreach($showcaseCollection as $singleCollection){ 
$_product =  Mage::getModel('catalog/product')->load($singleCollection->getProductId());
$productBlock = $this->getLayout()->createBlock('catalog/product_price');
$designId=$singleCollection->getId();
?>
<li class="item first col-xs-12 col-sm-4" style="list-style: none;">
	<div class="grid_wrapper">
		<a href="<?php echo $this->getUrl('admin_showcase/adminhtml_showcasebackend/edit/',array('id' => $designId)); ?>" title="<?php echo $singleCollection->getProductName(); ?>" >
				<?php 
			$imageUrl = $singleCollection->getImageUrl(); 
			if (empty($imageUrl)) 
			{
				$imageUrl = Mage::getSingleton('catalog/product_media_config')->getBaseMediaUrl(). '/placeholder/' .Mage::getStoreConfig("catalog/placeholder/small_image_placeholder");
			} 
		?>
		<img src="<?php echo $imageUrl; ?>" alt="<?php echo $singleCollection->getProductName(); ?>">
		
		</a>
		<div class="product-shop">
			<?php echo $productBlock->getPriceHtml($_product); ?>
			<span>ID <?php echo $singleCollection->getId(); ?> </span>
			<h2 class="product-name">
				<?php echo $singleCollection->getProductName(); ?>
			</h2>
			<div class="desc_grid">Designed by <?php echo $singleCollection->getCustomerName(); ?></div>
			<form method="post" action="<?php echo $this->getUrl('admin_showcase/adminhtml_showcasebackend/save'); ?>">
				<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
				<input type="hidden" name="id" value="<?php echo $singleCollection->getId(); ?>" />
				<div class="desc_grid">
					<?php if($singleCollection->getIsActive()) { ?>
					<button type="submit" class="add-to-showcase">Remove From Showcase</a>
					<input type="hidden" name="is_active" value="0" />
					<?php } else { ?>
					<button type="submit" class="add-to-showcase">Add to Showcase</a>
					<input type="hidden" name="is_active" value="1" />
					<?php }  ?>
				</div>
			</form>
		</div>
		<div class="label-product">             
		</div>
	</div>
</li>
<?php 
$count++;
if($count%6==0){ ?>
	</ul><ul class="products-grid row odd">
	<?php
}
} ?>
</ul>	
</div>
<div class="full-width-container">
<div class="page-title category-title">
        <h1>Customer Designs not in Showcase</h1>
</div>

<?php 
$showcaseCollection = Mage::getModel('showcase/showcase')->getCollection()->addFieldToFilter('is_active',0)->setOrder('created_at', 'desc');
$count=0;
?>
<ul class="products-grid row odd">
<?php foreach($showcaseCollection as $singleCollection){ 
$_product =  Mage::getModel('catalog/product')->load($singleCollection->getProductId());
$productBlock = $this->getLayout()->createBlock('catalog/product_price');
?>
<li class="item first col-xs-12 col-sm-4" style="list-style: none;">
	<div class="grid_wrapper">
		<a href="<?php echo $this->getUrl('admin_showcase/adminhtml_showcasebackend/edit/',array('id' => $designId)); ?>" title="<?php echo $singleCollection->getProductName(); ?>" >
		<?php 
			$imageUrl = $singleCollection->getImageUrl(); 
			if (empty($imageUrl)) 
			{
				$imageUrl = Mage::getSingleton('catalog/product_media_config')->getBaseMediaUrl(). '/placeholder/' .Mage::getStoreConfig("catalog/placeholder/small_image_placeholder");
			} 
		?>
		<img src="<?php echo $imageUrl; ?>" alt="<?php echo $singleCollection->getProductName(); ?>">
		
		
		</a>
		
		
		<div class="product-shop">
			<?php echo $productBlock->getPriceHtml($_product); ?>
			<!--<div class="price-box">
				<span class="regular-price" id="product-price-1611">
					<span class="price">$7.50</span>
				</span>
			</div>-->
			<span>ID <?php echo $singleCollection->getId(); ?> </span>
			<h2 class="product-name"><!--<a href="<?php echo $singleCollection->getLink(); ?>?pj=<?php echo $singleCollection->getPjnumber(); ?>" title="<?php echo $singleCollection->getProductName(); ?>">--><?php echo $singleCollection->getProductName(); ?><!--</a>--></h2>
			<div class="desc_grid">Designed by <?php echo $singleCollection->getCustomerName(); ?></div>
			<form method="post" action="<?php echo $this->getUrl('admin_showcase/adminhtml_showcasebackend/save'); ?>">
			<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
			<input type="hidden" name="id" value="<?php echo $singleCollection->getId(); ?>" />
			<div class="desc_grid">
			<?php if($singleCollection->getIsActive()) { ?>
			<button type="submit" class="add-to-showcase">Remove From Showcase</a>
			<input type="hidden" name="is_active" value="0" />
			<?php } else { ?>
			<button type="submit" class="add-to-showcase">Add to Showcase</a>
			<input type="hidden" name="is_active" value="1" />
			<?php }  ?>
			</div>
			</form>
		</div>
		<div class="label-product">             
		</div>
	</div>
</li>
<?php 
$count++;
if($count%6==0){ ?>
	</ul><ul class="products-grid row odd">
	<?php
}
} ?>
</ul>	
</div>