<?	
	$detect = new Gateway3D_PersonaliseIt_Helper_MobileDetect;
	$isMobile = $detect->isMobile() && !$detect->isTablet();
	
	$urlKey = $isMobile ? 'mobile_iframe_url' : 'iframe_url';
	
	$url = trim(Mage::getStoreConfig("general/personaliseit-product-selector/{$urlKey}"));
	
	if($isMobile && !$url)
	{
		$url = trim(Mage::getStoreConfig("general/personaliseit-product-selector/iframe_url"));
	}
	
	$epa = rawurlencode(Mage::getUrl('personaliseit/product/epa'));
	$callback = rawurlencode(Mage::getUrl('personaliseit/product/callback'));
?>

<iframe style="border: 0; width: 100%; height: 100%;" src="<?= $url ?>&a2cpost=1&epa=<?= $epa ?>&ep3dUrl=<?= $callback ?>"></iframe>